version: '3.8'
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@johnston.host"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker-data/traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.johnston.host`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    volumes:
      - "./docker-data/nginx/website:/usr/share/nginx/html:ro"
      - "./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`johnston.host`) || Host(`mail.johnston.host`) || Host(`www.johnston.host`)"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  autodiscover:
    image: "monogramm/autodiscover-email-settings:latest"
    container_name: "autodiscover"
    environment:
      - COMPANY_NAME=johnston.host
      - SUPPORT_URL=https://autodiscover.johnston.host
      - DOMAIN=johnston.host
      # IMAP configuration (host mandatory to enable)
      - IMAP_HOST=mail.johnston.host
      - IMAP_PORT=143
      - IMAP_SOCKET=STARTTLS
      # SMTP configuration (host mandatory to enable)
      - SMTP_HOST=mail.johnston.host
      - SMTP_PORT=587
      - SMTP_SOCKET=STARTTLS
      # MobileSync/ActiveSync configuration (url mandatory to enable)
      - MOBILESYNC_URL=https://sync.johnston.host
      - MOBILESYNC_NAME=sync.johnston.host
      # LDAP configuration (host mandatory to enable)
      #- LDAP_HOST=ldap.johnston.host
      #- LDAP_PORT=636
      #- LDAP_SOCKET=SSL
      #- LDAP_BASE=dc=ldap,dc=example,dc=com
      #- LDAP_USER_FIELD=uid
      #- LDAP_USER_BASE=ou=People,dc=ldap,dc=example,dc=com
      #- LDAP_SEARCH=(|(objectClass=PostfixBookMailAccount))
      # Apple mobile config identifiers (identifier mandatory to enable)
      - PROFILE_IDENTIFIER=host.johnston.autodiscover
      - PROFILE_UUID=92943D26-CAB3-4086-897D-DC6C0D8B1E86
      - MAIL_UUID=7A981A9E-D5D0-4EF8-87FE-39FD6A506FAC
      #- LDAP_UUID=6ECB6BA9-2208-4ABF-9E60-4E9F4CD7309E
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autodiscover.rule=Host(`autoconfig.johnston.host`) || Host(`autodiscover.johnston.host`) || Host(`sync.johnston.host`)"
      - "traefik.http.routers.autodiscover.entrypoints=websecure"
      - "traefik.http.routers.autodiscover.tls.certresolver=myresolver"

  mailserver:
    image: "docker.io/mailserver/docker-mailserver:latest"
    container_name: "mailserver"
    # If the FQDN for your mail-server is only two labels (eg: johnston.host),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: "mail"
    domainname: "johnston.host"
    environment:
    # https://github.com/docker-mailserver/docker-mailserver/blob/v10.3.0/docs/content/config/environment.md
      - ENABLE_AMAVIS=0
      - SSL_TYPE=letsencrypt
      - POSTFIX_INET_PROTOCOLS=ipv4
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - "./docker-data/dms/mail-data/:/var/mail/"
      - "./docker-data/dms/mail-state/:/var/mail-state/"
      - "./docker-data/dms/mail-logs/:/var/log/mail/"
      - "./docker-data/dms/config/:/tmp/docker-mailserver/"
      - "./docker-data/traefik/acme.json:/etc/letsencrypt/acme.json:ro"
      - "./docker-data/dms/config/dovecot/10-custom.conf:/etc/dovecot/conf.d/10-custom.conf"
      - "./docker-data/dms/certs/:/certs"
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    labels:
      - "traefik.enable=false"

  watchtower:
    restart: always
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
